### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by ipepe** [rtfpessoa/dependency_spy#3]
Hacktoberfest is here. Are there any issues that You would like to be helped with?

**Comment by rtfpessoa** [comment]
Hi @ipepe that is a great idea. I already had tough about it but time is always an issue.
Since you brought it up, I quickly tried to add some ideas I had to the issues.
Feel free to do them or add new ones.

Some that are always ongoing might be improving docs and adding more tests.

Also, anything you find cumbersome while using, or that you feel is important might be a good idea to add.

Let me know if you have any questions.

I will also try to improve the CI workflows to be more contributor frendly soon specially when I tackle https://github.com/rtfpessoa/yavdb/issues/1.

**Comment by rtfpessoa** [comment]
Created #4, #5, #6, #7, #8, #9.

**Comment by rtfpessoa** [comment]
Also created some issues in https://github.com/rtfpessoa/yavdb/issues
